import { Link, useParams } from 'react-router-dom'
import { Button, Card, EmptyState } from '../components/ui'
import { useAppSelector } from '../store/hooks'

export function Home() { return <div className="space-y-8"><div className="rounded-2xl bg-indigo-700 px-6 py-12 text-white"><p className="text-sm font-semibold uppercase tracking-wide text-indigo-200">Студенческая жизнь рядом</p><h1 className="mt-3 max-w-2xl text-4xl font-bold">Находите события, которые вдохновляют</h1><p className="mt-4 max-w-xl text-indigo-100">Каталог мероприятий CampusHub готов к подключению REST API.</p><Link to="/events" className="mt-6 inline-block rounded-lg bg-white px-4 py-2 font-semibold text-indigo-700">Открыть каталог</Link></div><div className="grid gap-4 md:grid-cols-3">{['Поиск и фильтры', 'Регистрация студентов', 'Модерация организаторов'].map((text) => <Card key={text}><h2 className="font-semibold">{text}</h2><p className="mt-2 text-sm text-slate-500">Расширяемый UI-каркас без притворной серверной логики.</p></Card>)}</div></div> }

export function Events() { const events = useAppSelector((s) => s.events.items); return <div className="space-y-5"><div><h1 className="text-3xl font-bold">Мероприятия</h1><p className="mt-1 text-slate-500">Публичный каталог опубликованных событий.</p></div><div className="grid gap-3 md:grid-cols-4"><input aria-label="Поиск по названию" placeholder="Поиск..." className="rounded-lg border px-3 py-2 md:col-span-2" /><select className="rounded-lg border px-3 py-2" aria-label="Категория"><option>Все категории</option></select><select className="rounded-lg border px-3 py-2" aria-label="Формат"><option>Все форматы</option></select></div>{events.length ? events.map((event) => <Card key={event.id}><Link to={`/events/${event.id}`} className="text-lg font-semibold text-indigo-700">{event.title}</Link><p className="mt-2 text-slate-500">{event.description}</p></Card>) : <EmptyState title="Пока нет опубликованных событий" description="Когда API будет подключён, здесь появятся мероприятия." />}</div> }

export function EventDetails() { const { id } = useParams(); return <div className="space-y-5"><Link to="/events" className="text-sm text-indigo-700">← К каталогу</Link><Card><p className="text-sm text-slate-500">Мероприятие #{id}</p><h1 className="mt-2 text-3xl font-bold">Детали мероприятия</h1><p className="mt-4 text-slate-600">Данные будут загружаться через API-клиент. Здесь будут описание, дата, формат, место и регистрация.</p><Button className="mt-6" disabled>Зарегистрироваться</Button></Card></div> }

export function Login() { return <AuthForm title="Вход" submit="Войти" /> }
export function Register() { return <AuthForm title="Регистрация" submit="Создать аккаунт" /> }
function AuthForm({ title, submit }: { title: string; submit: string }) { return <Card className="mx-auto max-w-md"><h1 className="text-2xl font-bold">{title}</h1><form className="mt-6 space-y-4"><label className="block text-sm font-medium">Email<input type="email" required className="mt-1 w-full rounded-lg border px-3 py-2" /></label><label className="block text-sm font-medium">Пароль<input type="password" required minLength={6} className="mt-1 w-full rounded-lg border px-3 py-2" /></label><Button type="submit">{submit}</Button></form><p className="mt-4 text-xs text-slate-500">Форма подготовлена для интеграции JWT API; реальная авторизация не заявляется.</p></Card> }

export function Profile() { const user = useAppSelector((s) => s.auth.user); return <Card><h1 className="text-2xl font-bold">Профиль</h1><p className="mt-4">Пользователь: {user?.name}</p><p>Email: {user?.email}</p><p>Роль: {user?.role}</p></Card> }
export function Favorites() { return <EmptyState title="Избранное пусто" description="События, отмеченные студентом, появятся здесь." /> }
export function MyEvents() { return <div className="space-y-5"><div className="flex items-center justify-between"><h1 className="text-3xl font-bold">Мои мероприятия</h1><Link to="/events/create" className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Создать</Link></div><EmptyState title="Мероприятий пока нет" description="Черновики и статусы организатора будут загружаться из API." /></div> }
export function CreateEvent() { return <Card><h1 className="text-2xl font-bold">Создать мероприятие</h1><form className="mt-6 grid gap-4 md:grid-cols-2"><input required placeholder="Название" className="rounded-lg border px-3 py-2" /><input type="datetime-local" className="rounded-lg border px-3 py-2" /><textarea placeholder="Описание" className="rounded-lg border px-3 py-2 md:col-span-2" rows={4} /><Button type="submit" className="md:col-span-2">Сохранить черновик</Button></form></Card> }
export function Admin() { return <div className="space-y-5"><h1 className="text-3xl font-bold">Администрирование</h1><div className="grid gap-4 md:grid-cols-3">{['Модерация событий', 'Категории', 'Пользователи'].map((item) => <Card key={item}><h2 className="font-semibold">{item}</h2><p className="mt-2 text-sm text-slate-500">Раздел готов к подключению API.</p></Card>)}</div></div> }

